version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"
